"""Init and doctor helpers for local configuration."""

from __future__ import annotations

import secrets
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional, Sequence

from riji_agent.config import Settings
from riji_agent.integrations.hermes_installer import status as hermes_bridge_status
from riji_agent.paths import default_data_dir
from riji_agent.service import ServiceStatus, get_default_service_status

DEFAULT_PRESET = "feishu-hermes-deepseek"


@dataclass(frozen=True)
class DoctorResult:
    ok: bool
    messages: Sequence[str]


def write_init_env(
    env_file: Path,
    *,
    preset: str,
    journal_root: Optional[Path] = None,
    data_dir: Optional[Path] = None,
    deepseek_api_key: str = "replace-me",
    feishu_user_ids: Sequence[str] = ("ou_replace_me",),
    hermes_shared_secret: Optional[str] = None,
    force: bool = False,
) -> None:
    if preset != DEFAULT_PRESET:
        raise ValueError("unsupported preset")
    if env_file.exists() and not force:
        raise FileExistsError(str(env_file))

    secret = hermes_shared_secret or secrets.token_urlsafe(32)
    journal = str(journal_root or Path("/absolute/path/to/your/Obsidian/riji"))
    data = str(data_dir or default_data_dir())
    users = ",".join(feishu_user_ids)

    body = "\n".join(
        [
            "# Generated by riji-agent init --preset feishu-hermes-deepseek",
            f"RIJI_JOURNAL_ROOT={journal}",
            f"RIJI_DATA_DIR={data}",
            "RIJI_IM_PROVIDER=feishu",
            "RIJI_AGENT_RUNTIME=hermes",
            "RIJI_MODEL_PROVIDER=deepseek",
            f"DEEPSEEK_API_KEY={deepseek_api_key}",
            "DEEPSEEK_BASE_URL=https://api.deepseek.com",
            "DEEPSEEK_MODEL=deepseek-reasoner",
            f"RIJI_ALLOWED_FEISHU_USER_IDS={users}",
            f"HERMES_SHARED_SECRET={secret}",
            "HERMES_BASE_URL=http://127.0.0.1:3000",
            "RIJI_PORT=8765",
            "",
        ]
    )
    env_file.write_text(body, encoding="utf-8")


def run_doctor(
    *,
    env_file: Path = Path(".env"),
    service_status_provider: Callable[[], ServiceStatus] = get_default_service_status,
) -> DoctorResult:
    messages = []
    ok = True

    if not env_file.exists():
        return DoctorResult(False, ("env: missing", "configuration: invalid"))
    messages.append("env: found")

    try:
        settings = Settings(_env_file=str(env_file))
    except Exception:
        return DoctorResult(False, tuple(messages + ["configuration: invalid"]))

    messages.append("configuration: ok")

    try:
        settings.ensure_data_directory()
        messages.append("data_dir: ok")
    except Exception:
        ok = False
        messages.append("data_dir: invalid")

    if _sqlite_fts5_available():
        messages.append("sqlite_fts5: ok")
    else:
        ok = False
        messages.append("sqlite_fts5: unavailable")

    try:
        bridge = hermes_bridge_status()
        messages.append(f"hermes_bridge: {bridge.state}")
    except Exception:
        messages.append("hermes_bridge: unknown")

    try:
        service = service_status_provider()
        messages.append(_format_service_status(service))
    except Exception:
        messages.append("service: unknown")

    messages.append(f"model_provider: {settings.model_provider}")
    return DoctorResult(ok, tuple(messages))


def _sqlite_fts5_available() -> bool:
    try:
        conn = sqlite3.connect(":memory:")
        try:
            conn.execute("CREATE VIRTUAL TABLE docs USING fts5(content)")
        finally:
            conn.close()
    except sqlite3.Error:
        return False
    return True


def _format_service_status(status: ServiceStatus) -> str:
    if not status.installed:
        return "service: not installed"
    if status.running:
        return f"service: running pid={status.pid} health={status.health}"
    if status.loaded:
        return f"service: loaded health={status.health}"
    return "service: stopped"
